feat: add devbox

diff --git a/.github/actions/commons/action.yml b/.github/actions/commons/action.yml
--- a/.github/actions/commons/action.yml
+++ b/.github/actions/commons/action.yml
@@ -11,25 +11,21 @@ runs:
       run: git config --global user.name "K.I.T.T."
       shell: bash
 
-    - name: Setup PHP
-      uses: shivammathur/setup-php@v2
+    - name: Install devbox
+      uses: jetify-com/devbox-install-action@v0.9.0
       with:
-        php-version: '8.3'
+        enable-cache: 'true'
+    - name: Load devbox via direnv
+      uses: HatsuneMiku3939/direnv-action@v1
 
-    - name: Read .nvmrc
+    - name: Check xdebug config
+      shell: bash
       run: |
-        echo "##[set-output name=NODE_VERSION;]$(cat .nvmrc| grep -oE '[0-9]+(\.[0-9]+)?(\.[0-9]+)?' | head -1)"
-      shell: bash
-      id: node_version
-    - name: Setup Node.js
-      uses: actions/setup-node@v4
-      with:
-        node-version: |
-          ${{ steps.node_version.outputs.NODE_VERSION }}
+        if ! php --info | grep 'xdebug.mode => develop => develop'; then
+          echo 'Error: xdebug.mode should not be set in CI. Have you committed xdebug config by accident? Check devbox.d/php/php.ini'
+          exit 1
+        fi
 
-    - name: Install pnpm
-      run: npm install -g pnpm@8
-      shell: bash
     - name: Tell pnpm to use Bash
       run: pnpm config set script-shell /bin/bash
       shell: bash
